version: '3'
services:
  db:
    # コンテナ名の指定
    container_name: rails_todoapl_db
    image: mysql:5.7
    # DBのレコードが日本語だと文字化けするので、utf8をセットする
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    # ローカルにDBを持つ
    volumes:
      - ./tmp/db:/var/lib/mysql

  webapl:
    # コンテナ名の指定
    container_name: rails_todoapl_webapl
    build: .
    image: rails_image
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "sh launch.sh"
    volumes:
      - .:/todoapp
      - public-data:/todoapp/public
      - tmp-data:/todoapp/tmp
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    # コンテナ名の指定
    container_name: rails_todoapl_nginx
    build:
      context: ./nginx
    volumes:
      - public-data:/todoapp/public
      - tmp-data:/todoapp/tmp
    ports:
      - 80:80
    depends_on:
      - webapl

volumes:
  public-data:
  tmp-data:
